spring:
  datasource:
    username: APEVDES
  atlas:
    obfuscation:
      active: true
      specific-sensitive-fields:
        - name: 'amount'
          config[0]:
            minLength: 1
channel:
  body:
    loansimulation:
      tasaspf: 1.4
